#ifndef _CONFIG_KEYLOGGER_H
#define _CONFIG_KEYLOGGER_H

#define KEYLOGGER_TASK_STACK_SIZE 2048

#define KEYLOGGER_PRINT_KEY_BUFFER_SIZE 4096

#define KEYLOGGER_UART_QUEUE_LENGTH 30
#define KEYLOGGER_KEY_QUEUE_LENGTH 30

#define KEYLOGGER_UART_PORT_NUM 1
#define KEYLOGGER_UART_BAUD_RATE 115200
#define KEYLOGGER_UART_RXD 18
#define KEYLOGGER_UART_TXD 17
#define KEYLOGGER_UART_RX_BUFFER_SIZE 2048

typedef int keylogger_err_t;
typedef enum
{
    KEYLOGGER_SUCCESS = 1,
    KEYLOGGER_FAIL
} keylogger_err_code;

#endif